version: '3.8'

services:
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    # COMMANDE EXPLICITE : On lance la classe Java du Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" # UI Web
      - "7077:7077" # Port de communication interne
    volumes:
      - ./src:/opt/spark/work-dir # Le dossier change (plus de /opt/bitnami)

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    # COMMANDE EXPLICITE : On lance le Worker en lui donnant l'adresse du Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./src:/opt/spark/work-dir

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"        # Port API (pour Spark)
      - "9001:9001"        # Port Console (pour toi)
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: